# Generated by Django 5.2.6 on 2025-09-08 16:37

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upi_id',
            field=models.CharField(help_text='UPI ID must be in the format of username@domain', max_length=255, null=True, unique=True, validators=[users.utils.upi_validation]),
        ),
    ]
